[tool.commitizen]
name = "cz_conventional_commits"
version_provider = "cargo"
version_scheme = "semver"
tag_format = "v$version"
annotated_tag = true
major_version_zero = true
update_changelog_on_bump = true
changelog_incremental = true
changelog_file = "CHANGELOG.md"
