#!/usr/bin/env ruby
# frozen_string_literal: true

# Generates the ISF rendering coefficients used by SurroundFold from the
# companion C tables published with ETSI TS 103 190-2.

abort "usage: #{$PROGRAM_NAME} ts_103190_tables_part2.c output.rs" unless ARGV.length == 2

source_path, output_path = ARGV
source = File.read(source_path)
input_layouts = {
  "SR3100" => 4,
  "SR5300" => 8,
  "SR7300" => 10,
  "SR9500" => 14,
  "SR7530" => 15,
  "SR15951" => 30
}.freeze
output_layouts = {
  "2" => 2,
  "5" => 5,
  "7" => 7,
  "702" => 9,
  "704" => 11,
  "904" => 13
}.freeze

generated = +<<~RUST
  // Generated by scripts/generate-isf-tables.rb from the coefficient tables
  // accompanying ETSI TS 103 190-2 V1.3.1. Do not edit by hand.
  #![allow(clippy::excessive_precision, clippy::unreadable_literal)]

RUST

output_layouts.each do |output_name, output_count|
  input_layouts.each do |input_name, input_count|
    c_name = "#{input_name}_to_#{output_name}"
    body = source[/float\s+#{c_name}\s*\[[^\]]+\]\[[^\]]+\]\s*=\s*\{(.*?)\n\};/m, 1]
    abort "could not find #{c_name}" unless body

    values = body.scan(/[+-]?\d+\.\d+e[+-]\d+f/i).map { |value| value.sub(/f\z/i, "_f32") }
    expected = input_count * output_count
    abort "#{c_name} contains #{values.length} values; expected #{expected}" unless values.length == expected

    rust_name = c_name.upcase
    generated << "#[rustfmt::skip]\n"
    generated << "pub(crate) const #{rust_name}: [f32; #{expected}] = [\n"
    values.each_slice(output_count) do |row|
      generated << "    #{row.join(', ')},\n"
    end
    generated << "];\n\n"
  end
end

File.write(output_path, generated)
